### ISSUE TITLE
sidekiq won't install on scalable app

### ISSUE THREAD

**Issue by smonetti** [openshift-cartridges/openshift-origin-cartridge-sidekiq#1]
I am trying to add this cartridge to an app that is set to scale in OpenShift and it's giving me the following error.

$ rhc add-cartridge https://raw2.github.com/openshift-cartridges/openshift-origin-cartridge-sidekiq/0.0.3/metadata/manifest.yml --app [app_name]

The cartridge 'https://raw2.github.com/openshift-cartridges/openshift-origin-cartridge-sidekiq/0.0.3/metadata/manifest.yml' will be downloaded and installed

Adding https://raw2.github.com/openshift-cartridges/openshift-origin-cartridge-sidekiq/0.0.3/metadata/manifest.yml to application '[app_name]' ... **Cartridges ["mfojtik-sidekiq-2.17.3", "ruby-1.9"] cannot be grouped together as they scale individually**

**Comment by lyneux** [comment]
Same problem!

**Comment by jorgevbo** [comment]
Me too!

**Comment by nathanielks** [comment]
Still encountering this with Ruby 2.0 😢 
```
$ rhc add-cartridge http://cartreflect-claytondev.rhcloud.com/github/pranavpr/openshift-origin-cartridge-sidekiq --app test
The cartridge 'http://cartreflect-claytondev.rhcloud.com/github/pranavpr/openshift-origin-cartridge-sidekiq' will be downloaded and installed
Adding http://cartreflect-claytondev.rhcloud.com/github/pranavpr/openshift-origin-cartridge-sidekiq to application 'test1' ... Cartridges ["pranavpr-sidekiq-3.3.1", "ruby-2.0"] cannot be grouped together as they scale individually
```

**Comment by nathanielks** [comment]
@developercorey wanted to check in and see if you saw this?

**Comment by developercorey** [comment]
@nathanielks This cartridge is out of date and probably will not be updated anytime soon.

**Comment by nathanielks** [comment]
@developercorey noted. Are there any docs available on how to get Sidekiq set up using your platform? All the googling I've done points to using this cartridge.
